### ISSUE TITLE
Is uglifyjs-webpack-plugin necessary for webpack V4

### ISSUE THREAD

**Issue by hec9527** [ruanyf/webpack-demos#101]
By the default pack mode of webpack, is production. And this `bundle.js` is minified.

I tried run demo08 by `webpack` command,  and demo06, Both the `bundle.js` minified.

demo06 use `Uglifyjs-webpack-plugin`  and demo08 not, just use `webpack`

So, is `Uglifyjs-webpack-plugin` necessary for webpack since V4 ?

**Comment by ruanyf** [comment]
You are right.

Since 4.x version，Webpack will default compress the output file in the production mode.
