### ISSUE TITLE
Too few cases

### ISSUE THREAD

**Issue by sowhahahaaha** [ruanyf/webpack-demos#103]
Too few cases
There are too few cases, can we have more

**Comment by leslie0507** [comment]
谢谢你的回复，我会尽快回复的

**Comment by huanghezhou** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhangyongjian986** [comment]
您的邮件已收到，我将尽快回复，谢谢！

**Comment by ruanyf** [comment]
This project is no longer developed. You may choose tools other than Webpack.
