### ISSUE TITLE
Cleaner demos without React?

### ISSUE THREAD

**Issue by dmitriz** [ruanyf/webpack-demos#15]
It would be nice to have simple demos dedicated to single purpose each, without React or any other external resources that do not serve the main purpose of the individual demo.

**Comment by ruanyf** [comment]
The following demos don't use React:
- Demo01
- Demo02
- Demo04
- Demo05

Since React maximizing the power of Webpack, I really feel they should be used together.

**Comment by dmitriz** [comment]
How can React maximize the power of Webpack? Isn't it the other way around? :)

**Comment by ruanyf** [comment]
In my opinion, if we use Webpack with native JavaScript, there are not much
difference between Webpack and Browserify.
