### ISSUE TITLE
DEMO09，run error.

### ISSUE THREAD

**Issue by JiayangShen** [ruanyf/webpack-demos#16]
I run the following command in Win7 cmd:

`env DEBUG=true webpack-dev-server`

and the cmd show: 'env' is not a internal or external command ...

**Comment by ruanyf** [comment]
use it under Linux/Mac.

**Comment by JiayangShen** [comment]
Is there any way to use it under Windows?

**Comment by ruanyf** [comment]
You should find how to export a variable into a child process under Windows
command line.

**Comment by JiayangShen** [comment]
Thanks! And I found a easier way to run demo09 under windows os, just run `set DEBUG=true` before run `webpack-dev-server` in cmd.

**Comment by JiayangShen** [comment]
Add this os difference notice in these demos' docs may help many beginers.

**Comment by ruanyf** [comment]
Thanks for your contribution. I already updated README.
