### ISSUE TITLE
阮老师,webpack-dev-server可以设置成手机也能访问么?

### ISSUE THREAD

**Issue by mqliutie** [ruanyf/webpack-demos#17]
使用`webpack-dev-server` 打开的是 `localhost:8080`
我的内网地址是'10.0.0.21', 我直接替换成'10.0.0.21:8080'是不能访问的,
那有没有什么机制可以更改呢?如果改成这个手机和电脑在同一局域网,就可以手机调试了

**Comment by ruanyf** [comment]
这是你的内网设置啊，跟`webpack-dev-server`没关系啊。

**Comment by chollaflower** [comment]
webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors --host 0.0.0.0 --port 8080

指定--host为0.0.0.0就可以了，和内网无关。
