### ISSUE TITLE
missing installation  webpack-dev-server

### ISSUE THREAD

**Issue by wanghaisheng** [ruanyf/webpack-demos#2]
pls add the following in readme

```
npm install -g webpack-dev-server or 
sudo npm install -g webpack-dev-server 
```

**Comment by ruanyf** [comment]
webpack-dev-server is in `package.json` as devDependencies. `npm install` should install it.

**Comment by wanghaisheng** [comment]
sorry for that  ,i am using zsh and npm install does not work well,
if you type webpack-dev-server  to run, it will throw a command not found
