### ISSUE TITLE
Could we rename the "demoX" folders to declarative names?

### ISSUE THREAD

**Issue by khanghoang** [ruanyf/webpack-demos#25]
Hi, I appreciate what you've done so far, I love it. But i think it will be great for newbie if we can rename the "demoX" folder to declarative names so that they can have a very quick look.

Let me know if you think it makes sense.

**Comment by ruanyf** [comment]
I am intended to keep these demos in order. If their names were changed to the description, it will be difficult to find which one after which one. 

Perhaps, `01-entry-file`, `02-multiple-entry-files`, ... is a possible solution. But it is wordy and hard to write.
