### ISSUE TITLE
能否添加一些output复杂一些的例子

### ISSUE THREAD

**Issue by lili21** [ruanyf/webpack-demos#27]
output的配置项特别多，不是很清楚用来干嘛的。

特别想知道的是path 与 publicPath。文档看的不是很理解。阮老师能提供个demo吗？

**Comment by ruanyf** [comment]
会的，output我讲得不清楚。

现成的例子看这里。基本上，path是构建生成的静态文件路径，publicPath是HTML页面调用的路径。

https://github.com/ruanyf/react-babel-webpack-boilerplate/blob/master/webpack.config.js

**Comment by lili21** [comment]
好快。
就是说，require('style.css') 最终在html上是 href=publicPath + 'style.css' ？。
