### ISSUE TITLE
react-router的一个问题

### ISSUE THREAD

**Issue by zouchengzhuo** [ruanyf/webpack-demos#29]
进入某个router后刷新，好像会报 Cannot GET /XXX ，我正在找原因

**Comment by ruanyf** [comment]
那是正常的，因为服务器端没做路由适配。

**Comment by zouchengzhuo** [comment]
明白了，我之前用angularJs，这次看到react的router下意识当成和angular-router一样的了，实际上angular-router用的是hash切换路由，react-router的是path...
