### ISSUE TITLE
webpack-dev-server not found!

### ISSUE THREAD

**Issue by agileago** [ruanyf/webpack-demos#3]
I follow the `readme` and i also find the package webpack-dev-server in node_modules.
but the bash show me `webpack-dev-server not found`

**Comment by agileago** [comment]
i find i should execute `npm install -g webpack-dev-server`. now it work

**Comment by ruanyf** [comment]
Thanks for your reminder.  Sorry with my carelessness.

I edited the HOW TO USE part in package.json. Now it should work for everyone.
