### ISSUE TITLE
demo16 控制台报Warning: render(): Rendering components directly into document.body is discouraged

### ISSUE THREAD

**Issue by huguangju** [ruanyf/webpack-demos#33]
> Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.

参见：http://my.oschina.net/wuguzi/blog/535378

**Comment by ruanyf** [comment]
It is just for convenience. If you don't like the warning, use `document.body.appendChild(document.createElement("div"))` instead.
