### ISSUE TITLE
热替换Demo15会页面刷新

### ISSUE THREAD

**Issue by w3cmark** [ruanyf/webpack-demos#34]
替换Demo15，自己测试发现是会刷新页面的，是搞错了吗？
我用的是第二种方式 webpack-dev-server
修改后页面是有更新，但是会刷新

**Comment by ruanyf** [comment]
没有重载页面，只是刷新组件。

我改了一下Demo，让它看起来更明显一点。

**Comment by w3cmark** [comment]
不知道是不是我这边的问题，我直接clone下来，测试的确是页面发生重载了，因为我看到network下的重新发出了所有请求。而我找到另一个demo，里面提到的热替换的体验是完全不一样的：
https://github.com/gaearon/react-hot-loader 。

2016-02-23 11:35 GMT+08:00 Ruan YiFeng notifications@github.com:

**Comment by ruanyf** [comment]
我的理解是，由于变更的是服务器端代码，所以请求是会重新发出的。

关键是页面不重载，只刷新单个组件，同时保持状态不变。

**Comment by w3cmark** [comment]
今天我电脑出问题，刚好重新装了系统，然后重新装了node和webpack-dev-server，然后运行第一种命令 $
webpack-dev-server --hot --inline，可以达到不刷新而替换内容的效果了，感谢您的回答！

在 2016年2月23日 下午2:03，黎军 lijungm305@gmail.com写道：
