### ISSUE TITLE
使用demo过程的一些问题

### ISSUE THREAD

**Issue by mingliao** [ruanyf/webpack-demos#35]
感谢您提供这么好的例子，不过不知道是否是版本更新的问题，在学习的过程中发现了这些问题。
1.demo08 不用书写html源文件，在实际的演示过程中，并没有出现预期的结果（包含hello wold的index.html）。仅显示服务器[webpack-dev-server]的js文件列表页
2.demo09 我使用的是window环境，
但是命令行输入DEBUG=true webpack-dev-server，提示没有这个命令debug[cmder无法识别这个命令]。需要再另外安装别的软件么？

**Comment by ruanyf** [comment]
`demo08`在我的机器上是正常的，但是我没在windows测试过。

`demo09`你用`set DEBUG=true webpack-dev-server`，可以吗？
