### ISSUE TITLE
demo9 测试发现DEBUG=true webpack-dev-server   不可用

### ISSUE THREAD

**Issue by mask2012** [ruanyf/webpack-demos#37]
windows环境

demo9 测试发现DEBUG=true webpack-dev-server   不可用

报错为
'DEBUG' 不是内部或外部命令，也不是可运行的程序或批处理文件。

请问需要额外安装什么吗？

**Comment by YuchenShen** [comment]
改成 set DEBUG=true  webpack-dev-server

**Comment by mask2012** [comment]
0 ，这么玩的啊，感谢感谢！

**Comment by coolskull** [comment]
set DEBUG=true webpack-dev-server运行之后为什么没有输出任何东西

**Comment by mask2012** [comment]
分两句执行

**Comment by coolskull** [comment]
恩，分两步确实可以，谢谢阮老师
