### ISSUE TITLE
demo08 error

### ISSUE THREAD

**Issue by jackPanyj** [ruanyf/webpack-demos#41]
when i run demo08 , it reports errors.

  demo08 git:(master) ✗ webpack-dev-server
http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /home/yanjie/Public/github/webpack-demos/demo08
Hash: fc2be4484e3356d26c56
Version: webpack 1.13.0
Time: 76ms
     Asset      Size  Chunks             Chunk Names
 bundle.js   1.43 kB       0  [emitted]  main
index.html  52 bytes          [emitted]  
chunk    {0} bundle.js (main) 40 bytes [rendered]
    [0] ./main.js 40 bytes {0} [built]

ERROR in Path must be a string. Received undefined
webpack: bundle is now VALID.

**Comment by ruanyf** [comment]
Don't use Node 6.x now. use 4.x / 5.x instead.

**Comment by holidaying** [comment]
如果用了node6应该怎么解决问题？

**Comment by ruanyf** [comment]
update to Node 7.x
