### ISSUE TITLE
demo13里面关于第三方插件不合并的问题

### ISSUE THREAD

**Issue by lczxhf** [ruanyf/webpack-demos#45]
你好！我试了您的ｄｅｍｏ１３！但是有些疑问！
１．您在ｏｕｔｆｉｌｅ里面最后生成了两个ｊｓ文件。一个ｖｅｎｄｏｒ.js里面包含了ｊｑｕｅｒｙ的！，但是在ｍｉａｎ.js里面又ｒｅｑｕｉｒｅ了ｊｑｕｅｒｙ,所以的话，bundle。ｊｓ里面也包含了ｊｑｕｅｒｙ！这样不会重复了吗？
２．我去掉了ｄｅｍｏ１３里面ｍａｉｎ.js里面的　`var $= rquire("jquery")` 但是报了一个错就是$ 未定义

请问可以帮我解答一下吗？谢谢

**Comment by ruanyf** [comment]
webpack 打包生成的是 vendor.js 和 bundle.js

**Comment by lczxhf** [comment]
不好意思!字母不知道都变成中文的! 我重新发一遍:

你好！我试了您的demo13！但是有些疑问！

> 1.您在outfile里面最后生成了两个js文件。一个是vendor.js,一个是bundle.js
>        但是vendor里面就已经包含了jquery的！,
>        同时您又在main.js里面又require了jquery,所以的话,bundle.js里面也包含了jquery！
>        这样不会重复了吗？
> 
> ---
> 
> 2.我去掉了demo13里面main.js里面的　`var $= rquire("jquery")` 但是报了一个错就是$ 未定义

请问可以帮我解答一下吗？谢谢

**Comment by ruanyf** [comment]
你看一下 bundle.js 就明白了，它不包含 jQuery 的。
