### ISSUE TITLE
demo15热刷新没有效果

### ISSUE THREAD

**Issue by Lapsec** [ruanyf/webpack-demos#51]
按说明用webpack-dev-server跑起来后，改动js没有热刷新，而是直接刷新了。
chrome的控制台输出：[HMR] Waiting for update signal from WDS...

**Comment by front-end-john** [comment]
只是个demo而已，其他功能肯定要自己搞的吧

**Comment by ruanyf** [comment]
这个例子确实不明显，HMR的作用是刷新一个模块，其他模块不受影响。

这个例子里面，整个应用只有一个模块，导致它刷新，好像整个页面都刷新了。我再想想看，有没有更合适的例子。
