### ISSUE TITLE
README.md 里这个 git地址是不是需要更新了

### ISSUE THREAD

**Issue by wliday** [ruanyf/webpack-demos#52]
git clone git@github.com:ruanyf/webpack-demos.git
Cloning into 'webpack-demos'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (public key).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ruanyf** [comment]
Please make sure you have the permission to use this computer. 

It seemed you have no right to write in `~/.ssh/known_hosts`.
