### ISSUE TITLE
说好的汉语呢

### ISSUE THREAD

**Issue by ghost** [ruanyf/webpack-demos#54]
为么子全是英文，高大上的赶脚，就是看起来不是很方便啦，哈哈，同意的点个赞

**Comment by ruanyf** [comment]
等准备好了，就会有中文版教程，针对 Webpack 2.0 版。

**Comment by ghost** [comment]
@ruanyf  我以为大半夜看代码的只有苦逼的我一个，原来阮大神晚上回复这么神速，大神就是大神啊。顺便请教个问题，网上很多人说 webpack会取代fis以及requir跟sea.毕竟前端的水流的很快，迭代的速度都别学的还快，可是忙死了学的人。今天项目还在用sea,组长来一句都什么年代了还用sea,赶紧用webpack，就去你博客看了看。大神对这些有什么高见
