### ISSUE TITLE
大多demo跑不起来

### ISSUE THREAD

**Issue by yanlee26** [ruanyf/webpack-demos#56]
阮老师您好，这个问题什么原因呢，报错缺少某个包。是不是需要更新某些东西，非常感谢啦

**Comment by shuperry** [comment]
@yanlee26 你要先 `npm install` 或者直接 `npm i` 也可以，把包都装上了才能跑 demo 撒，npm 只是把包放在线上，让我们的项目源码里面不用放那么多东西而已，项目里面只需要配置你要用哪个包的哪个版本，在运行项目的时候才需要执行 `npm install` 把包从线上安装到项目中

**Comment by ruanyf** [comment]
如果有问题，请贴出报错信息。
