### ISSUE TITLE
Add a demo using import-loader

### ISSUE THREAD

**Issue by ramakrishnamundru** [ruanyf/webpack-demos#62]
Can yo u add a demo using the import-loader by following this example: http://reactkungfu.com/2015/10/integrating-jquery-chosen-with-webpack-using-imports-loader/ .

It will be very useful to know how to use jquery plugins with webpack.

Edit: also can you give a demo using providePlugin: https://webpack.github.io/docs/list-of-plugins.html#provideplugin

**Comment by ruanyf** [comment]
I think import-loader is not an elegant solution. You should use vendor chunk instead. https://github.com/ruanyf/webpack-demos#demo13-vendor-chunk-source
