### ISSUE TITLE
demo3 ERROR in ./main.jsx

### ISSUE THREAD

**Issue by youmyyou** [ruanyf/webpack-demos#65]
Module build failed: Error: Couldn't find preset "es2015" relative to directory
why?

**Comment by ruanyf** [comment]
Step One: If your webpack is v2.x, remove it and install v1.x.

Step Two: delete `node_modules` directory under the project root and re-install dependencies.

```bash
$ npm install
```

**Comment by youmyyou** [comment]
thank you!
I fixed it by adding a `.babelrc` file.
`{
    "presets": ["es2015", "react"]
}`
