### ISSUE TITLE
demo12抛异常了，什么原因导致的呢？

### ISSUE THREAD

**Issue by tlqylzn** [ruanyf/webpack-demos#69]
运行webpack-dev-server后抛错
![error](https://cloud.githubusercontent.com/assets/4860021/23251427/3bbd9952-f9e8-11e6-96c2-9965f957972f.png)

**Comment by ruanyf** [comment]
你删除 node_modules 目录，重装一下试试看。

https://discuss.circleci.com/t/node-module-not-found/5545
