### ISSUE TITLE
关于工程中对less文件的处理

### ISSUE THREAD

**Issue by fefuns** [ruanyf/webpack-demos#72]
你好，请教一下假如我的工程目录是
丨__build
丨__src
丨_____css
丨________a.less
丨________b.less

src是开发目录，在src/css下有很多 less文件，通常需要先将这多个less文件分别利用autoprefixer添加兼容前缀编译成css文件到  src/css 目录下，因为src开发目录是需要上传到gitlab的文件。最终，需要将之前生成的 src/css/*.css   文件 压缩合并成一个all.css文件到build/css目录下，这个all.css是线上的文件。请问这些操作我该如何利用webpack配置完成？

同理，其实还有src/images 中的图片也是要先压缩到  src/images/下，再输出到 build/images/目录下。相当于是得输出到多个目录下，请问如何解决？谢谢。

**Comment by ruanyf** [comment]
简单 less 编译，使用 webpack 的 less-loader 就可以了。复杂的操作，需要在 webpack 编译之前，对 less 文件单独做一次编译处理。

**Comment by fefuns** [comment]
....感觉很模糊啊....那请教下另一个问题呢？webpack怎么输出到多个目录，demo里面都是输出到同一个目录下的。比如src/images下的图片先压缩输出到src/images下，覆盖原有的图片，另外接着再输出到build/images目录下

**Comment by ruanyf** [comment]
我不会在 Webpack 里面做图片压缩，而是会用其他工具先压缩图片。然后，再调用 webpack。

```javascript
// package.json
{
  // ...
  "scripts": {
     "build": "imageProcesser && webpack"
  },
  // ...
}
```

**Comment by fefuns** [comment]
那如果不是具体指图片，webpack有方法输出到多个目录吗？目前基本都是可以有多个入口文件，然后统一都输出到了build目录下。我想先输出到src目录，再输出到build目录呢？

**Comment by ruanyf** [comment]
Webpack 本身好像不支持，也可能是我不知道。

但是，Loader 支持将某个类型的文件，放到另一个目录。你可以看看这个插件 https://github.com/kevlened/copy-webpack-plugin

**Comment by fefuns** [comment]
嗯，好的。谢谢。
