### ISSUE TITLE
第8个demo报错了

### ISSUE THREAD

**Issue by holidaying** [ruanyf/webpack-demos#73]
报的是插件的问题

**Comment by holidaying** [comment]
![Paste_Image.png](http://upload-images.jianshu.io/upload_images/2604175-5b9de07cdd6f479b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by ruanyf** [comment]
升级 Node 到 7.x，并且删掉 node_modules 目录，重新安装`npm install`。

**Comment by holidaying** [comment]
好的，多谢。还有一个问题请教
![Paste_Image.png](http://upload-images.jianshu.io/upload_images/2604175-0b476ca3144d2629.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
在项目中vue后缀的文件在src文件夹下，但是我在webpack中把src文件夹过滤掉了，构建的时候用require引入的时候没有报错，什么原因？我的理解是vue文件不是js文件，如果要用webpack加载必须使用loader转换，我既然把src目录过滤掉了，应该会报错的

**Comment by ruanyf** [comment]
我不太确定，感觉`resolve`的执行顺序优于`loader`。

**Comment by miaobug** [comment]
node -v 7.9.0
npm -v 4.5.0
demo08 still not work
