### ISSUE TITLE
there's something wrong when running demo12?

### ISSUE THREAD

**Issue by lessfish** [ruanyf/webpack-demos#76]
<img width="561" alt="demo12" src="https://cloud.githubusercontent.com/assets/10890665/25556168/a89f77d2-2d2a-11e7-894b-668e8322f811.png">

**Comment by ruanyf** [comment]
use webpack 1.x.

**Comment by lessfish** [comment]
Do you have the plan to upgrade to 2.x?

**Comment by ruanyf** [comment]
Maybe the second half year. I am too busy these days.
