### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by Atrbear** [ruanyf/webpack-demos#79]
ERROR in   TypeError: Cannot read property 'request' of undefined

  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33

  - ExternalModuleFactoryPlugin.js:46 next
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8

  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7

  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5

  - NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
    [npm]/[webpack]/lib/NormalModuleFactory.js:246:4

  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [npm]/[webpack]/[_tapable@0.2.6@tapable]/lib/Tapable.js:196:70

  - NormalModuleFactory.js:230 NormalModuleFactory.create
    [npm]/[webpack]/lib/NormalModuleFactory.js:230:8

  - Compilation.js:381 Compilation._addModuleChain
    [npm]/[webpack]/lib/Compilation.js:381:17

  - Compilation.js:463 Compilation.addEntry
    [npm]/[webpack]/lib/Compilation.js:463:8

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/SingleEntryPlugin.js:22:15

  - Tapable.js:229 Compiler.applyPluginsParallel
    [npm]/[webpack]/[_tapable@0.2.6@tapable]/lib/Tapable.js:229:14

  - Compiler.js:503 applyPluginsAsync.err
    [npm]/[webpack]/lib/Compiler.js:503:9

  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [npm]/[webpack]/[_tapable@0.2.6@tapable]/lib/Tapable.js:131:46

  - Compiler.js:496 Compiler.compile
    [npm]/[webpack]/lib/Compiler.js:496:8

  - Compiler.js:284 Compiler.runAsChild
    [npm]/[webpack]/lib/Compiler.js:284:8

  - compiler.js:70
    [webpack-demos]/[_html-webpack-plugin@2.29.0@html-webpack-plugin]/lib/compil    er.js:70:19

webpack: Failed to compile.

**Comment by ruanyf** [comment]
Please give out the details of your error: which demo? which version of webpack? which command you run?

**Comment by Atrbear** [comment]
@ruanyf  I am sorry, I installed the lastest version of the webpack and webpack-dev-server. And I reinstalled the 1.x version, it worked. Ps, it was demo08.
