### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by meishadevs** [ruanyf/webpack-demos#80]
阮老师您好，我最近在将您的项目 webpack-demos 的 README.md 文件翻译成中文，其中第13个demo的名称 `Vendor chunk` 不知道该如何翻译，请问这个该如何翻译
我翻译成中文的 README.md 的链接 [https://github.com/meishadevs/webpack-demos/blob/master/README.md](https://github.com/meishadevs/webpack-demos/blob/master/README.md)

**Comment by ruanyf** [comment]
Vendor 指开发商，我觉得“vendor chunk”译成“开发商代码块”或者“第三方代码块”，都行吧。

谢谢你的翻译，不过这些 Demo 还是 Webpack 1.x 版，有点过时了……

**Comment by meishadevs** [comment]
我觉得这个项目对于学习 Webpack 非常有帮助，至于版本比较老的问题，到时候可以升级成2.x版，如果遇到什么 bug 自己能解决升级过程中遇到的 bug 可以锻炼自己的能力
