### ISSUE TITLE
删除bundle.js文件

### ISSUE THREAD

**Issue by manbusiwei** [ruanyf/webpack-demos#82]
大神你好，最近初学webpack。想请教一下，生成的index.html文件是需要引入bundle.js的，但是我在学习的时候把这个文件删除了，重启服务，还是不影响。这是为什么呢？

**Comment by ruanyf** [comment]
webpack-dev-server 运行时会自动生成。

**Comment by ChuanChuanSu** [comment]
自动生成的时候不会创建本地文件吗？
