### ISSUE TITLE
can`t copy the repo on the mac

### ISSUE THREAD

**Issue by andyli666** [ruanyf/webpack-demos#84]
git clone git@github.com:ruanyf/webpack-demos.git
Cloning into 'webpack-demos'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

?
Thanks!

**Comment by SuperRay3** [comment]
There are many reasons for this problem. I used this method to slove it (on windows 10 environment), but I don't clearly konw if it works for you. Have a try!

1. First you'll want to cd into your .ssh directory. Open up the terminal and run:
`cd ~/.ssh && ssh-keygen`

2. copy SSH Key top the clipboard
OS X: `cat id_rsa.pub | pbcopy `
Linux: `cat id_rsa.pub | xclip`
Window: `cat id_rsa.pub | clip`

3.  open your github profile page, select `setting` -> `SSH Key and GPG Keys`

4. click `new SSH Key` 

5. Paste in `key` area and set a title you can recognize.

6. All things done

**Comment by ruanyf** [comment]
Using HTTPS will be OK.

```bash
$ git clone https://github.com/ruanyf/webpack-demos.git
```
