### ISSUE TITLE
demo14 :Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined

### ISSUE THREAD

**Issue by wand933** [ruanyf/webpack-demos#9]
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#cant-hot-reload
module.exports = {
    ....
    module: {
        loaders: [{
            test: /\.js$/,
            exclude:/node_modules/,
            ....
        }]
    }
};

**Comment by ruanyf** [comment]
cannot reproduce this error
