### ISSUE TITLE
老师，传统的多html页面的前端项目有没有办法用webpack搭建呢？

### ISSUE THREAD

**Issue by nikolausliu** [ruanyf/webpack-demos#93]
一个页面就是一个入口，入口太多了。
而且每个页面的<img>标签引用的静态资源可以被webpack识别到依赖图里吗？
这些都是问题，没有思路，还请老师提供一个思路，谢谢

**Comment by ruanyf** [comment]
可以啊。每个页面编译一个入口文件。https://github.com/ruanyf/webpack-demos#demo02-multiple-entry-files-source
