### ISSUE TITLE
can't run the demos

### ISSUE THREAD

**Issue by boboZh** [ruanyf/webpack-demos#97]
hi, i clone your project and did what you told, but it can't run 
there is the error log: 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle webpack-demo1@1.0.0~predev: webpack-demo1@1.0.0
6 info lifecycle webpack-demo1@1.0.0~dev: webpack-demo1@1.0.0
7 verbose lifecycle webpack-demo1@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle webpack-demo1@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yiche/WebstormProjects/webpack-demos/demo01/node_modules/.bin:/usr/local/bin:./usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yiche/WebstormProjects/webpack-demos/node_modules/.bin:/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin
9 verbose lifecycle webpack-demo1@1.0.0~dev: CWD: /Users/yiche/WebstormProjects/webpack-demos/demo01
10 silly lifecycle webpack-demo1@1.0.0~dev: Args: [ '-c', 'webpack-dev-server --open' ]
11 silly lifecycle webpack-demo1@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle webpack-demo1@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: webpack-demo1@1.0.0 dev: `webpack-dev-server --open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid webpack-demo1@1.0.0
15 verbose cwd /Users/yiche/WebstormProjects/webpack-demos/demo01
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.5.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error webpack-demo1@1.0.0 dev: `webpack-dev-server --open`
22 error Exit status 1
23 error Failed at the webpack-demo1@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

thank you!

**Comment by ruanyf** [comment]
No idea of the reason.
